#!/usr/bin/env python3
"""
Calibrate the ONE constant the P/b/D classifier turns on.

No published numeric cutoffs for these shapes exist -- the field teaches them
visually. So the threshold cannot be looked up, only chosen. This grounds the
choice against a published FREQUENCY instead of taste:

  Objective: pick the threshold whose resulting D (balanced) frequency is
  closest to 50% -- Dalton's base rate for normal/rotational days in
  "Mind Over Markets", the most-cited number in that taxonomy.

Why this objective:
  * it targets a published frequency, not a preference
  * it is OUTCOME-FREE -- no trade results enter it, so it is structurally
    incapable of overfitting to profit (see project_rsi_reversal_m1)
  * it is calibrated on GOLD, not inherited from index futures

Stated limits of the anchor: Dalton's day types are a different taxonomy from
P/b/D (his Normal Day is defined by initial-balance extension, not skew), and
his rates come from equity-index RTH sessions, not 23-hour gold. 50% is a
defensible prior, not ground truth. The P/b split is REPORTED, never targeted,
and the sweep is judged on having a broad plateau.

Usage:
  python scripts/calibrate_profile_shape.py
  python scripts/calibrate_profile_shape.py --ticks data/ticks/XAUUSD --row-size 0.10
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.microstructure import volume_profile as vp          # noqa: E402
from src.microstructure import profile_context as pc         # noqa: E402

TARGET_D_FREQ = 0.50
SWEEP = np.round(np.arange(0.05, 1.51, 0.05), 2)


def session_skews(tick_dir: Path, row_size: float, max_spread: float) -> list[float]:
    """One skew per session file. Sessions below the tick floor are skipped."""
    params = vp.ProfileParams(row_size=row_size, max_spread_usd=max_spread)
    out: list[float] = []
    files = sorted(tick_dir.glob("*.parquet"))
    if not files:
        raise SystemExit(f"no .parquet tick files under {tick_dir}")
    for f in files:
        df = pd.read_parquet(f, columns=["bid", "ask"])
        hist = vp.accumulate_ticks(df.bid.to_numpy(), df.ask.to_numpy(), params)
        if hist.accepted < params.min_session_ticks:
            print(f"  skip {f.name}: {hist.accepted} ticks < {params.min_session_ticks}")
            continue
        # Mirror the classifier's own degeneracy guard, so the population
        # calibrated on is exactly the population that gets lettered live.
        # Never fires at the default row size, but a coarse --row-size can
        # collapse a session into too few rows to read a shape from.
        if int(np.count_nonzero(hist.volumes)) < params.min_rows_for_shape:
            print(f"  skip {f.name}: only {np.count_nonzero(hist.volumes)} occupied rows")
            continue
        s = pc.profile_skew(hist)
        if s is not None:
            out.append(s)
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--ticks", default="data/ticks/XAUUSD")
    ap.add_argument("--row-size", type=float, default=0.10)
    ap.add_argument("--max-spread", type=float, default=1.00)
    ap.add_argument("--out", default="reports/volume_profile_shape_calibration.md")
    args = ap.parse_args()

    skews = session_skews(PROJECT_ROOT / args.ticks, args.row_size, args.max_spread)
    if not skews:
        raise SystemExit("no usable sessions")
    arr = np.asarray(skews)
    print(f"{arr.size} sessions, skew range {arr.min():+.3f} .. {arr.max():+.3f}")

    # Bands mirror classify_shape exactly: P is `skew <= -t`, b is `skew >= t`,
    # D is everything between. Exhaustive and disjoint for every t > 0.
    rows = []
    for t in SWEEP:
        d = int(np.sum(np.abs(arr) < t))
        p = int(np.sum(arr <= -t))
        b = int(np.sum(arr >= t))
        rows.append((float(t), d / arr.size, p / arr.size, b / arr.size))

    best = min(rows, key=lambda r: abs(r[1] - TARGET_D_FREQ))
    chosen = best[0]

    # Plateau width: how wide a band of thresholds keeps D within 5pp of target.
    near = [r[0] for r in rows if abs(r[1] - TARGET_D_FREQ) <= 0.05]
    plateau = (min(near), max(near)) if near else (chosen, chosen)

    lines = [
        "# Volume Profile Shape Calibration",
        "",
        "**Generated by `scripts/calibrate_profile_shape.py` — do not hand-edit.**",
        "Hand-tuning the threshold below turns a calibrated constant back into a guess.",
        "",
        f"- Sessions used: **{arr.size}**",
        f"- Row size: `{args.row_size}` · max spread: `{args.max_spread}`",
        f"- Skew range: `{arr.min():+.3f}` .. `{arr.max():+.3f}`",
        f"- Objective: D frequency closest to **{TARGET_D_FREQ:.0%}** (Dalton, *Mind Over Markets*)",
        "",
        f"## Chosen threshold: `{chosen:.2f}`",
        "",
        f"- Achieved D frequency: **{best[1]:.1%}** (target {TARGET_D_FREQ:.0%})",
        f"- Resulting P: {best[2]:.1%} · b: {best[3]:.1%}  *(reported, not targeted)*",
        f"- Plateau within 5pp of target: `{plateau[0]:.2f}` .. `{plateau[1]:.2f}`",
        "",
        "⚠️ Dalton's day types are a DIFFERENT taxonomy from P/b/D, and his base",
        "rates come from equity-index RTH sessions rather than 23-hour gold. The",
        "50% target is a defensible prior, not ground truth. Judge this",
        "calibration on the width of the plateau above, not on hitting 50%.",
        "",
        "## Sweep",
        "",
        "| threshold | D | P | b |",
        "|---:|---:|---:|---:|",
    ]
    for t, d, p, b in rows:
        mark = " **<-**" if t == chosen else ""
        lines.append(f"| {t:.2f}{mark} | {d:.1%} | {p:.1%} | {b:.1%} |")

    out_path = PROJECT_ROOT / args.out
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n")
    print(f"\nchosen threshold {chosen:.2f} (D={best[1]:.1%}, plateau "
          f"{plateau[0]:.2f}..{plateau[1]:.2f}) -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
