#!/usr/bin/env python3
"""
Liquidity race calibration study.

Walks XAUUSD 15m history, builds the live level set at every snapshot, labels which
member was touched first inside 24h (or none), fits a conditional logit with an
outside option, and grades it against a distance-only baseline on a day-blocked
out-of-sample slice.

The point of the day-blocking: 24h forward windows overlap 95-deep, so the effective
independent sample is the number of DAYS, not the number of snapshots. Naive standard
errors here would be ~10x too optimistic — the same trap that produced the RSI-reversal
"12/12 plateau" that then scored PF 0.39 on a fresh holdout.

Writes:
  reports/liquidity_race_calibration.md
  mt5_indicators/liquidity_coefficients.mqh     (generated — never hand-edit)

Snapshots default to hourly (--stride 4). Per-bar snapshots are ~4x slower and buy
nothing: the windows overlap 95-deep either way, so the independent sample is the day
count, which stride does not change.

Usage:
  python scripts/research_liquidity_race.py                        # full run, hourly
  python scripts/research_liquidity_race.py --stride 16 --quick    # fast dev iteration
"""
from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.microstructure import liquidity_levels as ll          # noqa: E402
from src.microstructure import liquidity_race as lr            # noqa: E402

CSV = PROJECT_ROOT / "data/historical/XAUUSD_5m_real.csv"
REPORT = PROJECT_ROOT / "reports/liquidity_race_calibration.md"
MQH = PROJECT_ROOT / "mt5_indicators/liquidity_coefficients.mqh"

LAMBDAS = [0.0, 1e-4, 1e-3, 1e-2, 1e-1, 1.0, 10.0]
DIST_COL = ll.FEATURE_NAMES.index("log_dist_atr")

ECE_LIMIT = 0.05          # spec leg 2: expected calibration error <= 5pp
DECILE_LIMIT = 0.10       # spec leg 2: no decile off by more than 10pp


def load_15m(csv_path: Path) -> pd.DataFrame:
    df = pd.read_csv(csv_path, parse_dates=["timestamp"], index_col="timestamp")
    if df.index.tz is None:
        df.index = df.index.tz_localize("UTC")
    bars = (df.resample("15min", label="left", closed="left")
            .agg({"open": "first", "high": "max", "low": "min",
                  "close": "last", "volume": "sum"})
            .dropna(subset=["open", "high", "low", "close"]))
    flat = (bars.high == bars.low) & (bars.volume == 0)
    return bars[~flat]


def choose_lambda(data: lr.ChoiceData, n_folds: int = 5) -> tuple[float, list[dict]]:
    """Day-blocked CV on IS only. OOS is never consulted here."""
    folds = lr.day_block_folds(data.day_id, n_folds=n_folds, seed=17)
    trace = []
    best_lam, best_score = LAMBDAS[0], float("inf")
    for lam in LAMBDAS:
        scores = []
        for mask in folds:
            train = lr.subset(data, ~mask)
            valid = lr.subset(data, mask)
            if train.n_snap == 0 or valid.n_snap == 0:
                continue
            beta = lr.fit_conditional_logit(train, lam=lam)
            scores.append(lr.log_loss(beta, valid))
        mean = float(np.mean(scores)) if scores else float("inf")
        trace.append({"lam": lam, "cv_log_loss": mean})
        if mean < best_score:
            best_lam, best_score = lam, mean
    return best_lam, trace


def hit_vector(data: lr.ChoiceData) -> np.ndarray:
    """Per-row boolean: was THIS level the one touched first?"""
    hit = np.zeros(data.X.shape[0], dtype=bool)
    picked = data.chosen[data.chosen >= 0]
    hit[picked] = True
    return hit


def emit_mqh(path: Path, beta, mean, std, mode: str, platt: tuple[float, float],
             banner: str, calib_window: str, metrics: dict) -> None:
    def arr(name, vals):
        body = ",\n   ".join(f"{v: .10e}" for v in vals)
        return f"const double {name}[LQ_N_FEATURES] = {{\n   {body}\n}};\n"

    lines = [
        "//+------------------------------------------------------------------+",
        "//| liquidity_coefficients.mqh                                       |",
        "//| GENERATED by scripts/research_liquidity_race.py — DO NOT EDIT.   |",
        "//| Regenerating this file is the only sanctioned way the weights    |",
        "//| change. Hand-tuning it turns a calibrated model into a guess.    |",
        "//+------------------------------------------------------------------+",
        f"//  generated      : {datetime.now(timezone.utc):%Y-%m-%d %H:%M} UTC",
        f"//  calibration    : {calib_window}",
        f"//  effective N    : {metrics['oos_days']} OOS days "
        f"({metrics['oos_snapshots']} snapshots — the days are what count)",
        f"//  OOS log-loss   : model {metrics['oos_ll_model']:.5f} "
        f"vs distance {metrics['oos_ll_base']:.5f}",
        f"//  OOS top-1      : model {metrics['oos_top1_model']:.4f} "
        f"vs distance {metrics['oos_top1_base']:.4f}",
        f"//  bootstrap 95%  : [{metrics['ci_lo']:+.5f}, {metrics['ci_hi']:+.5f}] "
        f"(model - baseline log-loss; must be entirely < 0)",
        f"//  OOS ECE        : {metrics['ece']:.4f}   worst decile "
        f"{metrics['worst_decile']:.4f}",
        f"//  gate leg 1     : {'PASS' if metrics['leg1'] else 'FAIL'}",
        f"//  gate leg 2     : {'PASS' if metrics['leg2'] else 'FAIL'}",
        "//+------------------------------------------------------------------+",
        "#ifndef LIQUIDITY_COEFFICIENTS_MQH",
        "#define LIQUIDITY_COEFFICIENTS_MQH",
        "",
        f"#define LQ_N_FEATURES {len(beta)}",
        f'#define LQ_MODEL_MODE "{mode}"',
        "",
        "// Feature order is a hard contract with "
        "src/microstructure/liquidity_levels.py::FEATURE_NAMES:",
    ]
    lines += [f"//   {i:>2}  {n}" for i, n in enumerate(ll.FEATURE_NAMES)]
    lines += [
        "",
        arr("LQ_BETA", beta),
        arr("LQ_MEAN", mean),
        arr("LQ_STD", std),
        f"const double LQ_PLATT_A = {platt[0]: .10e};",
        f"const double LQ_PLATT_B = {platt[1]: .10e};",
        f'const string LQ_BANNER = "{banner}";',
        f'const string LQ_CALIB_WINDOW = "{calib_window}";',
        "",
        "#endif // LIQUIDITY_COEFFICIENTS_MQH",
    ]
    path.write_text("\n".join(lines) + "\n")


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--is-start", default="2022-01-01")
    p.add_argument("--is-end", default="2025-12-31")
    p.add_argument("--oos-start", default="2026-01-01")
    p.add_argument("--oos-end", default="2026-07-31")
    p.add_argument("--stride", type=int, default=4,
                   help="snapshot every Nth 15m bar (4 = hourly, the default; 1 = every "
                        "bar close, ~4x slower for no statistical gain — the effective "
                        "sample is DAYS, not snapshots)")
    p.add_argument("--horizon", type=int, default=96, help="forward bars (96 = 24h)")
    p.add_argument("--bootstrap", type=int, default=2000)
    p.add_argument("--quick", action="store_true",
                   help="skip the lambda CV and use 1e-3 (dev only, never for a ship)")
    args = p.parse_args()

    bars = load_15m(CSV)
    print(f"bars {len(bars):,}  {bars.index[0]} -> {bars.index[-1]}")

    def note(snap, t, n):
        print(f"  ... {snap:,} snapshots (bar {t:,}/{n:,})", flush=True)

    data, meta = ll.build_dataset(bars, ll.DEFAULTS, horizon=args.horizon,
                                  stride=args.stride, progress=note)
    print(f"snapshots {data.n_snap:,}  rows {data.X.shape[0]:,}")
    if data.n_snap == 0:
        print("no snapshots — check the data range")
        return 1

    ts = meta.groupby("snap_id").snapshot_ts.first().to_numpy()
    ts = pd.DatetimeIndex(ts)
    is_mask = (ts >= pd.Timestamp(args.is_start, tz="UTC")) & \
              (ts <= pd.Timestamp(args.is_end, tz="UTC"))
    oos_mask = (ts >= pd.Timestamp(args.oos_start, tz="UTC")) & \
               (ts <= pd.Timestamp(args.oos_end, tz="UTC"))
    print(f"IS snapshots {int(is_mask.sum()):,} ({len(np.unique(data.day_id[is_mask]))} days)"
          f"  OOS {int(oos_mask.sum()):,} ({len(np.unique(data.day_id[oos_mask]))} days)")
    if is_mask.sum() == 0 or oos_mask.sum() == 0:
        print("empty IS or OOS slice — check --is-start / --oos-start against the data")
        return 1

    is_data_raw = lr.subset(data, is_mask)
    oos_data_raw = lr.subset(data, oos_mask)

    # z-score constants come from IS only — OOS must not touch the fit in any way
    mean, std = lr.zscore_fit(is_data_raw.X)
    is_data = lr.ChoiceData(lr.zscore_apply(is_data_raw.X, mean, std),
                            is_data_raw.snap_id, is_data_raw.chosen, is_data_raw.day_id)
    oos_data = lr.ChoiceData(lr.zscore_apply(oos_data_raw.X, mean, std),
                             oos_data_raw.snap_id, oos_data_raw.chosen, oos_data_raw.day_id)

    def distance_only(d: lr.ChoiceData) -> lr.ChoiceData:
        return lr.ChoiceData(d.X[:, [DIST_COL]], d.snap_id, d.chosen, d.day_id)

    lam, cv_trace = (1e-3, []) if args.quick else choose_lambda(is_data)
    print(f"lambda {lam}")

    beta = lr.fit_conditional_logit(is_data, lam=lam)
    beta_base = lr.fit_conditional_logit(distance_only(is_data), lam=lam)

    oos_ll_model = lr.log_loss(beta, oos_data)
    oos_ll_base = lr.log_loss(beta_base, distance_only(oos_data))
    top1_model, cond_model = lr.top1_accuracy(beta, oos_data)
    top1_base, cond_base = lr.top1_accuracy(beta_base, distance_only(oos_data))
    diff, ci_lo, ci_hi = lr.day_block_bootstrap_diff(
        beta, beta_base, oos_data, distance_only(oos_data),
        n_reps=args.bootstrap, seed=23)

    leg1 = (oos_ll_model < oos_ll_base) and (top1_model > top1_base) and (ci_hi < 0.0)

    p_rows, _ = lr.predict_probs(beta, oos_data)
    hits = hit_vector(oos_data)
    table = lr.reliability(p_rows, hits, n_bins=10)
    ece = lr.expected_calibration_error(table)
    worst = float(table.gap.abs().max()) if len(table) else float("nan")
    leg2 = (ece <= ECE_LIMIT) and (worst <= DECILE_LIMIT)

    platt = (1.0, 0.0)
    platt_note = "none"
    if leg1 and not leg2:
        # Platt is fitted on IS predictions only, then re-checked on OOS
        p_is, _ = lr.predict_probs(beta, is_data)
        a, b = lr.platt_scale(p_is, hit_vector(is_data))
        p_cal = lr.platt_apply(p_rows, a, b)
        table_cal = lr.reliability(p_cal, hits, n_bins=10)
        ece_cal = lr.expected_calibration_error(table_cal)
        worst_cal = float(table_cal.gap.abs().max())
        platt_note = (f"fitted on IS (a={a:.4f}, b={b:.4f}); "
                      f"OOS ECE {ece:.4f} -> {ece_cal:.4f}")
        if ece_cal <= ECE_LIMIT and worst_cal <= DECILE_LIMIT:
            platt, table, ece, worst, leg2 = (a, b), table_cal, ece_cal, worst_cal, True

    if leg1 and leg2:
        mode = "full"
        banner = "Liquidity race: calibrated model active."
    elif not leg1 and leg2:
        mode = "distance"
        banner = ("Liquidity race: enriched model did NOT beat distance OOS — "
                  "showing the distance-only baseline probability.")
    else:
        mode = "rank_only"
        banner = ("Liquidity race: model is uncalibrated OOS — showing rank badges "
                  "only, no probability.")

    if mode == "distance":
        # bake the baseline into the same 12-slot vector so MQL5 stays one code path
        ship_beta = np.zeros(len(ll.FEATURE_NAMES))
        ship_beta[DIST_COL] = beta_base[0]
    else:
        ship_beta = beta

    metrics = dict(
        oos_days=int(len(np.unique(oos_data.day_id))),
        oos_snapshots=int(oos_data.n_snap),
        oos_ll_model=oos_ll_model, oos_ll_base=oos_ll_base,
        oos_top1_model=top1_model, oos_top1_base=top1_base,
        ci_lo=ci_lo, ci_hi=ci_hi, ece=ece, worst_decile=worst,
        leg1=leg1, leg2=leg2,
    )
    calib_window = f"IS {args.is_start}..{args.is_end} / OOS {args.oos_start}..{args.oos_end}"
    emit_mqh(MQH, ship_beta, mean, std, mode, platt, banner, calib_window, metrics)
    print(f"wrote {MQH}")

    write_report(REPORT, dict(
        bars=bars, data=data, is_data=is_data, oos_data=oos_data, meta=meta,
        lam=lam, cv_trace=cv_trace, beta=beta, beta_base=beta_base,
        mean=mean, std=std, table=table, metrics=metrics, mode=mode,
        banner=banner, platt_note=platt_note, diff=diff,
        cond_model=cond_model, cond_base=cond_base,
        calib_window=calib_window, stride=args.stride, horizon=args.horizon,
    ))
    print(f"wrote {REPORT}")
    print(f"\nMODE={mode}  leg1={'PASS' if leg1 else 'FAIL'}  "
          f"leg2={'PASS' if leg2 else 'FAIL'}")
    return 0


def write_report(path: Path, r: dict) -> None:
    m = r["metrics"]
    lines = [
        "# Liquidity Race — calibration report",
        "",
        f"Generated: {datetime.now(timezone.utc):%Y-%m-%d %H:%M} UTC  ",
        f"Data: `data/historical/XAUUSD_5m_real.csv` resampled to 15m, "
        f"{r['bars'].index[0]:%Y-%m-%d} → {r['bars'].index[-1]:%Y-%m-%d}  ",
        f"Split: {r['calib_window']}  ",
        f"Snapshot stride: {r['stride']} bar(s), horizon {r['horizon']} bars (24h)",
        "",
        f"## Verdict: `{r['mode']}`",
        "",
        f"> {r['banner']}",
        "",
        "| Gate | Requirement | Result | |",
        "|---|---|---|---|",
        f"| Leg 1 — beats distance | OOS log-loss lower | "
        f"{m['oos_ll_model']:.5f} vs {m['oos_ll_base']:.5f} | "
        f"{'PASS' if m['oos_ll_model'] < m['oos_ll_base'] else 'FAIL'} |",
        f"| | OOS top-1 higher | {m['oos_top1_model']:.4f} vs {m['oos_top1_base']:.4f} | "
        f"{'PASS' if m['oos_top1_model'] > m['oos_top1_base'] else 'FAIL'} |",
        f"| | day-block 95% CI excludes 0 | "
        f"[{m['ci_lo']:+.5f}, {m['ci_hi']:+.5f}] | "
        f"{'PASS' if m['ci_hi'] < 0 else 'FAIL'} |",
        f"| Leg 2 — calibrated | ECE ≤ 5pp | {m['ece'] * 100:.2f}pp | "
        f"{'PASS' if m['ece'] <= ECE_LIMIT else 'FAIL'} |",
        f"| | no decile off by > 10pp | {m['worst_decile'] * 100:.2f}pp | "
        f"{'PASS' if m['worst_decile'] <= DECILE_LIMIT else 'FAIL'} |",
        "",
        "## Sample-size honesty",
        "",
        f"- OOS snapshots: **{m['oos_snapshots']:,}**",
        f"- OOS effective N (distinct UTC days): **{m['oos_days']}**",
        "",
        "24h forward windows overlap 95-deep, so the effective independent sample is "
        "the number of days, not the number of snapshots. Every confidence interval "
        "above resamples whole days. Read the day count, not the snapshot count.",
        "",
        f"- Mean OOS log-loss difference (model − baseline): **{r['diff']:+.5f}** "
        f"(negative favours the model)",
        f"- OOS top-1 restricted to snapshots where something WAS touched: "
        f"model {r['cond_model']:.4f} vs baseline {r['cond_base']:.4f}",
        "",
        "## Fitted coefficients",
        "",
        f"L2 λ = `{r['lam']}` (day-blocked 5-fold CV on IS only)",
        "",
        "| # | feature | β (z-scored) | IS mean | IS std |",
        "|---|---|---|---|---|",
    ]
    for i, name in enumerate(ll.FEATURE_NAMES):
        lines.append(f"| {i} | `{name}` | {r['beta'][i]:+.4f} | "
                     f"{r['mean'][i]:+.4f} | {r['std'][i]:.4f} |")
    lines += ["", "Distance-only baseline β = "
              f"`{r['beta_base'][0]:+.4f}` on `log_dist_atr`.", ""]
    if r["cv_trace"]:
        lines += ["### λ selection (IS only)", "",
                  "| λ | CV log-loss |", "|---|---|"]
        lines += [f"| {t['lam']} | {t['cv_log_loss']:.5f} |" for t in r["cv_trace"]]
        lines.append("")
    lines += ["## Reliability (OOS)", "",
              f"Platt recalibration: {r['platt_note']}", "",
              "| decile | n | mean predicted | observed | gap |",
              "|---|---|---|---|---|"]
    for _, row in r["table"].iterrows():
        lines.append(f"| {int(row['bin'])} | {int(row['n']):,} | {row['p_mean']:.4f} | "
                     f"{row['observed']:.4f} | {row['gap']:+.4f} |")
    lines += ["", "## Level mix", "",
              "| kind | share of rows | share of first-touches |", "|---|---|---|"]
    meta = r["meta"]
    hits = hit_vector(r["data"])
    share = meta.kind.value_counts(normalize=True)
    hit_share = meta.loc[hits].kind.value_counts(normalize=True) if hits.any() else {}
    for kind in share.index:
        lines.append(f"| `{kind}` | {share[kind] * 100:.1f}% | "
                     f"{float(hit_share.get(kind, 0.0)) * 100:.1f}% |")
    lines += ["", "## Scope", "",
              "Research and chart only. Nothing here imports into `src/strategies`, "
              "`src/risk` or `src/execution`. If the calibration is strong, wiring it "
              "into a strategy is a separate decision behind the full `backtest.md` "
              "8-gate process.", ""]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))


if __name__ == "__main__":
    sys.exit(main())
