//+------------------------------------------------------------------+
//| liquidity_coefficients.mqh                                       |
//| GENERATED by scripts/research_liquidity_race.py — DO NOT EDIT.   |
//| Regenerating this file is the only sanctioned way the weights    |
//| change. Hand-tuning it turns a calibrated model into a guess.    |
//+------------------------------------------------------------------+
//  generated      : 2026-08-06 19:26 UTC
//  calibration    : IS 2022-01-01..2025-12-31 / OOS 2026-01-01..2026-07-31
//  effective N    : 165 OOS days (3343 snapshots — the days are what count)
//  OOS log-loss   : model 0.64589 vs distance 0.98969
//  OOS top-1      : model 0.7027 vs distance 0.6982
//  bootstrap 95%  : [-0.38478, -0.30082] (model - baseline log-loss; must be entirely < 0)
//  OOS ECE        : 0.0064   worst decile 0.0169
//  gate leg 1     : PASS
//  gate leg 2     : PASS
//+------------------------------------------------------------------+
#ifndef LIQUIDITY_COEFFICIENTS_MQH
#define LIQUIDITY_COEFFICIENTS_MQH

#define LQ_N_FEATURES 12
#define LQ_MODEL_MODE "full"

// Feature order is a hard contract with src/microstructure/liquidity_levels.py::FEATURE_NAMES:
//    0  log_dist_atr
//    1  n_closer_same_side
//    2  side_up
//    3  type_equal
//    4  type_session
//    5  log_age_bars
//    6  touch_count
//    7  trend_align
//    8  atr_pctile
//    9  session_london
//   10  session_ny
//   11  dist_x_atrpctile

const double LQ_BETA[LQ_N_FEATURES] = {
   -9.6444407360e-01,
   -4.6205623054e+00,
    2.9219510712e-02,
    3.1810071261e-02,
    5.5578801679e-02,
   -2.1660099824e-02,
    2.2627106564e-02,
   -3.6680125500e-02,
   -2.1571513840e+00,
    9.9116584714e-01,
    3.3899028558e-02,
    2.0816349433e-02
};

const double LQ_MEAN[LQ_N_FEATURES] = {
    1.4600559576e+00,
    1.4743095719e+00,
    4.8437082920e-01,
    3.1196742069e-02,
    6.0521542726e-01,
    3.5880312565e+00,
    5.6844050512e-01,
    5.0345984053e-01,
    5.0246009377e-01,
    4.2960199856e-01,
    3.7413503987e-01,
    7.4189089805e-01
};

const double LQ_STD[LQ_N_FEATURES] = {
    5.0983210866e-01,
    1.3926425516e+00,
    4.9975566932e-01,
    1.7384908787e-01,
    4.8880437178e-01,
    1.5854151698e+00,
    9.4377685617e-01,
    4.9998802936e-01,
    2.9886919902e-01,
    4.9501931416e-01,
    4.8389876194e-01,
    5.3734383645e-01
};

const double LQ_PLATT_A =  1.0000000000e+00;
const double LQ_PLATT_B =  0.0000000000e+00;
const string LQ_BANNER = "Liquidity race: calibrated model active.";
const string LQ_CALIB_WINDOW = "IS 2022-01-01..2025-12-31 / OOS 2026-01-01..2026-07-31";

#endif // LIQUIDITY_COEFFICIENTS_MQH
